name: GitHub Actions CI

run-name: ${{ github.event.head_commit.message }} ${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start CI workflow
        run: |
          echo "Starting CI workflow"
      - name: Set up Python
        run: |
          echo "Setting up Python"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          echo "Running tests"
          pytest
      - name: Run flake8
        run: |
          echo "Running flake8"
          flake8
      - name: Run isort
        run: |
          echo "Running isort"
          isort --check-only --diff
